# Generated by Django 5.2 on 2025-04-13 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('topic', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=255)),
                ('expiration_date', models.DateTimeField()),
                ('allows_anonymous_submission', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=255, null=True)),
                ('timestamp', models.DateTimeField()),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inbox')),
            ],
        ),
    ]
