# Generated by Django 5.2 on 2025-04-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_message_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
