# Generated by Django 5.2 on 2025-04-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_reply_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
